service: progenerator-service
app: progenerator-service
org: jefersonagudeloc

frameworkVersion: '2'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'test'}
  lambdaHashingVersion: 20201221
  environment:
      STAGE: "${self:provider.stage}"
      USER_TABLE_NAME: ${self:custom.UserTable.name}
  iamRoleStatements:
      - ${file(iam/UserTableIAM.yml):UserTableIAM}
  resources:
    Resources:
        UserTable: ${file(resources/UserTable.yml):UserTable}
functions:
  login:
    handler: src/handlers/session.login
    events:
      - http:
          method: POST
          path: /login
  createUser:
    handler: src/handlers/repository/user.create
    events:
      - http:
          method: POST
          path: /user
  getUser:
    handler: src/handlers/repository/user.get
    events:
      - http:
          method: GET
          path: /user/{id}
  hello:
    handler: handler.hello
custom:
  UserTable:
    name: !Ref UserTable
    arn: !GetAtt UserTable.Arn
  bundle:
    linting: false
  dynamodb:
    stages:
      - test
  serverless-offline:
    host: 0.0.0.0
    httpPort: 8282